


USE grandhoyal;
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('Amanda Aparecida Venancio', 1, 'amandaap@gmail.com', 'hospede', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('José Amado Silva', 1, 'joseamado@hotmail.com', 'hospede', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('Manoel Carlos Amado da Silva Pereira', 1, 'manoelcarlos@gmail.com', 'hospede', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('Carlos Eduardo de Pádua Silveira', 1, 'carlos@minhaempresa.com', 'hospede', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('Andréia de Castro Ferreira', 1, 'andreia123@icloud.com', 'hospede', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('Juliana Fonceca do Carmo Apolinário', 1, 'juliana_fonceca@negocios.com', 'hospede', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('Júlia Menezes Góis', 1, 'jmg21@gmail.com', 'hospede', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('Marcos Frederic Silveira', 1, 'marcos_frederic@icloud.com', 'hospede', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('Rafael Carvalho de Castro', 1, 'rafael_carvalho45685@negocios.com', 'hospede', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('Bianca Ferreira de Castro Menerva', 1, 'bianca123@hotmail.com', 'hospede', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('Hélio de Souza Parreira Vasconcelos', 1,	'heliosp777@icloud.com',	'hospede', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('Osvaldo Suzano do Perfeito Socorro', 1,	'Osvaldo@minhaempresa.com',	'hospede', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('Alana Santana Azevedo de Sousa', 1,	'alanasantana_aze@uol.com',	'hospede', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('Eliane Ferreira Lima', 1, 	'Stefanobriks@gmail.com',	'hospede', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('Geliane Stefano Brikstain', 1,	'geliane@outlook.com',	'hospede', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('Jeovana Gleice Coelho Peixoto', 1,	'jeovana456213@hotmail.com',	'hospede', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('Túlio Gardene Pereira Peixoto', 1,	'tuliogardene@icloud.com',	'hospede', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('Fernanda Cruz de Meneses', 1,	'fernanda123@uol.com',	'hospede', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('Maria Eduarda Venâncio Fonceca e Cruz', 1,	'maria_edu@hotmail.com',	'hospede', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('Madalena Eduarda Lourenço Paz', 1,	'madalenapaz@icloud.com',	'hospede', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('Bruna Camila Dávila de Deus', 1,	'brunacamila@negocios.com',	'hospede', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('Pedro Santos Rodrigues', 1,	'psr2121@hotmail.com',	'hospede', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('Carolina Ferreira Alves e Pereira', 1,	'carolina.ferreira@icloud.com',	'hospede', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('Pedro Gomes Costa Martins', 1,	'pedro_gomes456@uol.com',	'hospede', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('Divina Lopes Soares', 1,	'divina.lopes@icloud.com',	'hospede', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('Viviane Barbosa Vieira dos Santos', 1,	'vivi-bvs000@hotmail.com',	'hospede', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('Sandro Dias Nascimento Andrade', 1,	'sandro.dias@gmail.com',	'hospede', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('João Moreira Nunes',	'joao@business.com', 1,	'hospede', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('José Marques do Nascimento', 1,	'josemasques@gmail.com',	'hospede', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('Maria Machado de Freitas', 1,	'maria.machado@gmail.com',	'hospede', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('Paulo Ramos Gonçalves', 1,	'paulorg-@outlook.com',	'hospede', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('Daniela Cardoso Mendes', 1,	'danicardoso-me@hotmail.com',	'hospede', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('Patrícia Santana Ramos e Teixeira', 1,	'patricia.4582@gmail.com',	'hospede', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('Lúcia Nunes Andrade',	'lucia@yahoo.com', 1,	'hospede', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('Maurício Barbosa Vieira Dias', 1,	'barbosa.mauricio@gmail.com',	'hospede', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('Carmem Martins Gomes Lima', 1,	'carmemmgl@gmail.com',	'hospede', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('Cleusa Fernandes Lopes Barbosa', 1,	'cleusa.flb@gmail.com',	'hospede', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('Beatriz Moreira Marques',	'beatriz@yahoo.com', 1,	'hospede', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('Lucas Ferreira Carvalho Martins', 1,	'2020lucas@hotmail.com',	'hospede', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('Tiago Soares Dias Nascimento', 1,	'tiago.tiago@gmail.com',	'hospede', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('Nércia Martins Costa Gomes', 1,	'nerciagomes@gmail.com',	'hospede', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('Rodrigo Santos Oliveira Ferreira', 1,	'rodrigosof15889654788552@gmail.com',	'hospede', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('Emanuela Soares de Souza', 1,	 'emanuela@emanuela.com', 'funcionario', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('Aparecido do Bento Silva', 1,	 'aparecido@aparecido.com', 'funcionario', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('Fernanda Damasco de Paula', 1,	 'fernanda@email.com', 'funcionario', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('Luana de Castro Fernandes', 1,	 'luana@gmail.com', 'funcionario', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('Nilva Andrade de Jesus', 1,	 'nilva@nilva.com', 'funcionario', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('Paulo Alencastro Filho', 1,	 'paulo@paulo0.com', 'funcionario', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('Zeferino Aparecido Ferreira', 1,	 'zeze@email.com', 'funcionario', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('Carlos Borba Benedito', 1,	 'carlos@carlos.com', 'funcionario', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('Maria Machado de Freitas', 1, 	 'maria@maria.com', 'funcionario', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('Paulo Ramos Gonçalves',  1,	 'paulo123@paulo.com', 'funcionario', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('Daniela Cardoso Mendes', 1, 	 'dani@dani.com', 'funcionario', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('Patrícia Santana Ramos e Teixeira', 1, 	 'patricia@pati.com', 'funcionario', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('Lúcia Nunes Andrade', 1, 	 'lucia@lucia.com', 'funcionario', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('Maurício Barbosa Vieira Dias', 1, 	 'mauri@mauri.com', 'funcionario', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('Carmem Martins Gomes Lima',  1,	 'carmem@carmem.com', 'funcionario', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('Cleusa Fernandes Lopes Barbosa', 1, 	 'email@email.com', 'funcionario', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('Beatriz Moreira Marques', 1, 	 'email@email.com', 'funcionario', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('Lucas Ferreira Carvalho Martins', 1, 	 'email@email.com', 'funcionario', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('Tiago Soares Dias Nascimento', 1, 	 'email@email.com', 'funcionario', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('Márcia Martins Costa Gomes', 1, 	 'email@email.com', 'funcionario', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('Rodrigo Santos Oliveira Ferreira', 1, 	 'email@email.com', 'funcionario', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('Barbara Souza de Paula', 1, 	 'email@email.com', 'funcionario', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('Fernando Augusto Meneses', 1, 	 'email@email.com', 'funcionario', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('Isadora Venâncio da Cruz', 1, 	 'email@email.com', 'funcionario', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('Beatriz Andarade Aparecida', 1, 	 'email@email.com', 'funcionario', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('Antonio Bastos Batista', 1, 	 'email@email.com', 'funcionario', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('José de Freitas Ferreira', 1, 	 'email@email.com', 'funcionario', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('Eliane Ferreira Lima ', 1, 	'email@email.com', 'funcionario', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('Paulo Amado de Jesus', 1, 	 'email@email.com', 'funcionario', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('Janaína Barbosa Carvalho', 1, 	 'email@email.com', 'funcionario', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('Gabriel Duarte Pereira ', 1, 	 'email@email.com', 'funcionario', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('Izabela Muniz Castro Souza', 1, 	 'email@email.com', 'funcionario', NOW(), NOW() );
INSERT INTO pessoas (nome, ativo, email, role, createdAt, updatedAt) VALUES ('Enzo Albuquerque Almeida Alves', 1, 	 'email@email.com', 'funcionario', NOW(), NOW() );